import { NextResponse } from "next/server";
import { cookies } from "next/headers";

export async function POST(request: Request) {
  const cookieStore = await cookies();
  const token = cookieStore.get("spotify_access_token")?.value;

  if (!token) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  }

  const { songs, playlistName } = await request.json();

  // ia datele userului
  const userResponse = await fetch("https://api.spotify.com/v1/me", {
    headers: { Authorization: `Bearer ${token}` },
  });
  const tokenInfoResponse = await fetch("https://api.spotify.com/v1/me", {
    headers: { Authorization: `Bearer ${token}` },
  });
  console.log("Token scopes:", tokenInfoResponse.headers.get("x-oauth-scopes"));
  const user = await userResponse.json();

  // creeaza playlist ul
  const playlistResponse = await fetch(
    `https://api.spotify.com/v1/me/playlists`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: playlistName || "MoodQueue Playlist",
        description: "Generated by MoodQueue",
        public: true,
      }),
    }
  );
  const newPlaylist = await playlistResponse.json();

  if (newPlaylist.error) {
    return NextResponse.json({ error: newPlaylist.error }, { status: 403 });
  }

  // cauta fiecare melodie pe spotify
  const trackUris: string[] = [];
  for (const song of songs) {
    const searchResponse = await fetch(
      `https://api.spotify.com/v1/search?q=${encodeURIComponent(
        `${song.title} ${song.artist}`
      )}&type=track&limit=1`,
      {
        headers: { Authorization: `Bearer ${token}` },
      }
    );
    const searchData = await searchResponse.json();
    const track = searchData.tracks?.items?.[0];
    console.log("Track found:", track?.name, track?.uri);
    if (track) {
      trackUris.push(track.uri);
    }
  }

  console.log("Total tracks found:", trackUris.length);
  console.log("Playlist ID:", newPlaylist.id);
console.log("Token used:", token?.slice(0, 20));
  // adauga melodiile una cate una
for (const uri of trackUris) {
  await fetch(
    `https://api.spotify.com/v1/playlists/${newPlaylist.id}/tracks`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ uris: [uri] }),
    }
  );
}
return NextResponse.json({
  success: true,
  playlistUrl: newPlaylist.external_urls.spotify,
});
}